# Generated by Django 4.1.5 on 2023-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_id', models.IntegerField()),
                ('nama_depan', models.CharField(max_length=255)),
                ('nama_belakang', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
    ]
